version: '3'
services: 
  db:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: 'vcruads'
      MYSQL_ROOT_PASSWORD: 'HUz3ryh4EQh2'
    ports:
      - '3636:3306'
  app:
    restart: always
    build:
      context: '.'
      dockerfile: './docker/app/Dockerfile'
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html/
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini